services:
  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000"
    container_name: backend-app-container
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: backend-postgres-container
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    container_name: backend-redis-container
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
