services:
  postgres:
    image: postgres:16
    container_name: healthity-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:7.4.0
    container_name: healthity-redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network

volumes:
  postgres_data:
    name: healthity_postgres_data
  redis_data:
    name: healthity_redis_data

networks:
  backend_network:
    name: healthity_backend_net
